### ISSUE TITLE
DLNA/Cast to samsung smart tv not working

### ISSUE THREAD

**Issue by esseti** [captainyarr/popcorntime-ce-desktop#24]
Hi all,

I just noticed that the streaming directly to the TV (samsung smart, one of the latest) does not work anymore. The Cast (chromecast icon to explain) didn't work even before, but the DLNA did.

Anyone else with the same experience and hopefully a soluition?

**Comment by captainyarr** [comment]
I haven't been having any issues using with a Chromecast Ultra. I don't have a Samsung Smart TV to test against so its hard to review the issue.

**Comment by esseti** [comment]
ok, is there a way to see the log? beacuse the TV does nothing when i try to stream, so a log may be useful

**Comment by LipeDuoli** [comment]
Hi @captainyarr ,
I have this issue too.. here is the error log
```
[INFO] Loading torrent: ready
[INFO] Loading torrent: playingExternally
[INFO] Device IP: 192.168.1.105
[INFO] Available IPs: ["fe80::8956:a399:71f:ed56","172.28.91.113","fe80::95e4:f222:cf17:b496","192.168.1.100"]
[INFO] 192.168.1.100 picked for external playback
[ERROR] Error: Resource not found (716) Error: Resource not found (716)
    at E:\Programas\Popcorn-Time-CE\node_modules\upnp-mediarenderer-client\node_modules\upnp-device-client\index.js:141:21
    at ConcatStream.<anonymous> (E:\Programas\Popcorn-Time-CE\node_modules\concat-stream\index.js:37:43)
    at ConcatStream.emit (events.js:187:15)
    at finishMaybe (E:\Programas\Popcorn-Time-CE\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at afterWrite (E:\Programas\Popcorn-Time-CE\node_modules\readable-stream\lib\_stream_writable.js:492:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
win.error @ app.js:53
(anonymous) @ app.js:634
emit @ events.js:182
process._fatalException @ internal/bootstrap/node.js:438
```
My TV IP is 192.168.1.105

If you need tests, I can do it.. Just tell me which branch I need to clone..
