### ISSUE TITLE
Error opening external torrent file or magnetic link

### ISSUE THREAD

**Issue by LipeDuoli** [captainyarr/popcorntime-ce-desktop#34]
Hi,
Everytime I try to open an torrent for external file(drag the file to app window) or magnetic link(paste the url on the app window) I get an erro on console

opening an external file \\/
```
[INFO] Loading torrent
[ERROR] TorrentCache.handletorrent() error: Error: ENOENT: no such file or directory, open 'E:\Users\myuser\AppData\Local\Temp\Popcorn-Time\Deadpool.2.2018.Super.Duper.Cut.UNRATED.1080p.AMZN-CBR.WEB-DL.DDP5.1.H.264-NTG.torrent' /Users/liped/AppData/Local/Temp/Popcorn-Time/Deadpool.2.2018.Super.Duper.Cut.UNRATED.1080p.AMZN-CBR.WEB-DL.DDP5.1.H.264-NTG.torrent
[INFO] Loading torrent: Error resolving torrent.
[ERROR] TypeError: Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
    at child.onStateUpdate (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/views/player/loading.js:103:61)
    at triggerEvents (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:354:57)
    at triggerApi (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:339:19)
    at eventsApi (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:137:14)
    at Backbone.Model.Events.trigger (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:329:5)
    at Backbone.Model.set (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:498:16)
    at Object.updateState (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:279:28)
    at Object.handleError (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:275:22)
    at chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:139:37
    at ReadStream.done (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/common.js:51:13)
 ```
PS: I don't have or use the `E:\Users\myuser\AppData\Local\Temp\Popcorn-Time` directory. All my user files are in `C:\`. I don't now why the program is looking for this.

opening an magnetic link \\/
```
[INFO] Loading torrent
[ERROR] TorrentCache.resolve(): Unknown torrent type ?xt=urn:btih:e774b886539a3f7ebf1ffe7cd01a107f73298248&dn=Deadpool+2+(2018)+[BluRay]+[1080p]&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://zer0day.ch:1337&tr=udp://…1337&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://exodus.desync.com:6969
[INFO] Loading torrent: Error resolving torrent.
Uncaught TypeError: Cannot read property 'get' of undefined
    at child.onStateUpdate (loading.js:103)
    at triggerEvents (backbone.js:354)
    at triggerApi (backbone.js:339)
    at eventsApi (backbone.js:137)
    at Backbone.Model.Events.trigger (backbone.js:329)
    at Backbone.Model.set (backbone.js:498)
    at Object.updateState (torrent_cache.js:279)
    at Object.handleError (torrent_cache.js:275)
    at mod.pmod.resolve (torrent_cache.js:88)
    at handleTorrent (app.js:506)
[ERROR] TypeError: Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
    at child.onStateUpdate (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/views/player/loading.js:103:61)
    at triggerEvents (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:354:57)
    at triggerApi (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:339:19)
    at eventsApi (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:137:14)
    at Backbone.Model.Events.trigger (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:329:5)
    at Backbone.Model.set (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:498:16)
    at Object.updateState (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:279:28)
    at Object.handleError (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:275:22)
    at mod.pmod.resolve (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:88:22)
    at handleTorrent (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/app.js:506:44)
```

**Comment by captainyarr** [comment]
@LipeDuoli 

I can look into this a bit more when I get chance.

**Comment by captainyarr** [comment]
@LipeDuoli 

Fixed the issue in the latest develop branch.  Not sure if you are able to pull the latest and get the fix.
