### ISSUE TITLE
Error running "gulp build": SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by marcelpaulo** [captainyarr/popcorntime-ce-desktop#6]
While building from source, `gulp build` throws this error:
```
paulo@monk:~/src/desktop$ gulp build
/home/paulo/src/desktop/gulpfile.js:48
    return gulp.src('./build/Popcorn-Time-CE/linux64/*',)
                                                        ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/lib/nodejs/gulp/bin/gulp.js:118:3)
```

**Comment by captainyarr** [comment]
@marcelpaulo Thanks for pointing that out. I wasn't getting any errors on my side from that line. I'll push that into my develop
