### ISSUE TITLE
gulp build does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by legluondunet** [captainyarr/popcorntime-ce-desktop#62]
Hello,
when I launch gulp build, I obtain this error:

$ gulp build
[07:00:14] Using gulpfile ~/desktop/gulpfile.js
/usr/lib/nodejs/gulp/bin/gulp.js:132
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Thank you for your help.

**Comment by captainyarr** [comment]
Try this next time:

Use npx to launch gulp. NPX will launch the gulp version specifically

npx gulp build
npx gulp run
...

I've switched to gulp 4.0 so check the globally installed version if gulp 4.0

**Comment by legluondunet** [comment]
On ubuntu 18.04 it's the 3.9.1.6 version, I understood I can no more use gulp to build your PopcornTime version until Ubuntu update the version.

**Comment by legluondunet** [comment]
I can still start PT with this command:
npm install
npm start
